name: Generate GitHub Trophy

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  trophy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate trophy
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: codewithnofal
          output_path: /tmp/trophy.svg
          token: ${{ secrets.TROPHY_TOKEN }}
          theme: dracula

      - name: Publish trophy to output branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          cp /tmp/trophy.svg ./trophy.svg

          git fetch origin trophy-output || true

          git checkout --orphan trophy-output

          git rm -rf . || true

          git add trophy.svg
          git commit -m "Update GitHub trophy"
          git push origin trophy-output --force
