name: Update GitHub Trophy

on:
  schedule:
    - cron: "30 3 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  trophy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate trophy
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: codewithnofal
          output_path: assets/trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          theme: dracula

      - name: Commit trophy
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add assets/trophy.svg

          git diff --cached --quiet || git commit -m "Update GitHub trophy"

          git push
